language: node_js

node_js:
  - "4.1"

sudo: false

git:
  depth: 1

branches:
  except:
    - gh-pages

env:
  global:
    - REPO="git@github.com:g0v/summit.g0v.tw"
    - secure: "JhUJCf2L5ER8VPoeHDD5hSHkKNPAdc1ENVE2x0n9pClqgTTm0o4F6I7tRCoVzaWv7m5DAwANE6Kr7HJRcdrbevjKb+5YM+BUSeg2HJISUfa90omHIH8VeqyJYBgEeAL9TBV38BgRcuYn8pgUTiKwCBPxtoCW6ZGP2nu5449ZNK4="

after_success: .travis/after_success.sh
